"NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays" Wikipedia

# NumPy Arrays

In [2]:
#we start of by importing the numpy library
import numpy as np

In [3]:
#first of all lets look at how we can convert a list into a numpy array
List = [15,25,17,17,87,25]
type(List)

list

In [7]:
array = np.array(List)
array

array([15, 25, 17, 17, 87, 25])

In [8]:
#As we can see we created a numpy array based on a list
type(array)

numpy.ndarray

In [3]:
#one dimentional array is usually called a vector and two dimentaional array are matrices
vector = np.array([15,25,17,17,87,25])
matrices = np.array([[15,25,17,17,87,25],
                     [16,14,65,78,54,32]])

In [11]:
#an array from a start point till a stop point(not inclusive)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#an array from a start point till a stop point(not inclusive) with a step of 2
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#a vector of length 10 with 0 as a value
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
#a 4*4 matrice with 0 as a value
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#a vector of length 10 with 1 as a value
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#a 4*4 matrice with 1 as a value
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
#a matrix of a given shape with a given value to fill the matrix
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [91]:
np.empty((4,4))

array([[0.12196219, 0.44021222, 0.69901873, 1.38753861],
       [0.21975451, 1.41714486, 0.0132536 , 1.03831807],
       [0.8295422 , 0.6551191 , 0.71103433, 1.28047176],
       [1.29350182, 0.0068969 , 1.56626443, 0.00994371]])

In [16]:
#identity matrix(linear algebra)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#linspace returns an evenly spaced numbers on a given interval as an array
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [30]:
#an array of a given shape with random samples from a uniform distribution random floats between 0 and 1
np.random.rand(10)

array([0.14045915, 0.0867102 , 0.27256099, 0.53868176, 0.48993634,
       0.7656861 , 0.40561986, 0.08742264, 0.77825923, 0.29143916])

In [33]:
np.random.rand(4,4)

array([[0.33095223, 0.2360574 , 0.58632649, 0.97011773],
       [0.03280309, 0.2630907 , 0.04394743, 0.44037086],
       [0.07377301, 0.63248821, 0.13637486, 0.09231805],
       [0.47044707, 0.39782581, 0.99465286, 0.13352859]])

In [36]:
#an array of a given shape containning or samples from a normal distribution
np.random.randn(10)

array([ 0.09466186, -1.11852511,  1.33335565,  0.76656463,  0.78596195,
       -0.85862248, -0.36084253, -1.03061555,  0.50155315,  0.28000834])

In [37]:
np.random.randn(4,4)

array([[ 0.12196219,  0.44021222, -0.69901873,  1.38753861],
       [ 0.21975451, -1.41714486, -0.0132536 ,  1.03831807],
       [ 0.8295422 ,  0.6551191 ,  0.71103433, -1.28047176],
       [-1.29350182,  0.0068969 , -1.56626443, -0.00994371]])

In [39]:
#return a random value in a given interval the start point is inclusive but the stop point is not
np.random.randint(0,11)

9

In [42]:
#a vector of random values in a given interval the start point is inclusive but the stop point is not
np.random.randint(0,11,10)

array([10,  5,  2, 10, 10,  9,  1,  9,  0,  7])

In [41]:
#a 4*4 matrix of random values in a given interval the start point is inclusive but the stop point is not
np.random.randint(0,11,(4,4))

array([[ 6,  1,  1,  7],
       [10,  3,  4,  4],
       [ 9,  8,  8,  9],
       [ 2,  9,  0, 10]])

In [49]:
vec = np.random.randint(0,101,49)
vec

array([ 91,  13,  95,  18,  24,  75,  42,  12,  86,  72,  53,  42, 100,
        21,  72,  21,  58,  68,  12,  10,  65,  15,  66,  19,  92,  59,
        37,   4,  67,  84,  85,  51,  57,  21,  89,  84,  52,  53,  34,
         5,   7,  56,  26,  68,   9,  60,  46,  38,   1])

In [53]:
#now we will transform our vector into a 7*7 matrix
mat = vec.reshape(7,7)
mat

array([[ 91,  13,  95,  18,  24,  75,  42],
       [ 12,  86,  72,  53,  42, 100,  21],
       [ 72,  21,  58,  68,  12,  10,  65],
       [ 15,  66,  19,  92,  59,  37,   4],
       [ 67,  84,  85,  51,  57,  21,  89],
       [ 84,  52,  53,  34,   5,   7,  56],
       [ 26,  68,   9,  60,  46,  38,   1]])

# Numpy Statistics and operations

In [133]:
array = np.random.randint(0,101,10)
array

array([12, 72, 42, 75, 28,  1, 90, 95, 30, 56])

In [134]:
#append a value to our array
np.append(array,102)

array([ 12,  72,  42,  75,  28,   1,  90,  95,  30,  56, 102])

In [136]:
#insert a value at a given index
np.insert(array,0,103)

array([103,  12,  72,  42,  75,  28,   1,  90,  95,  30,  56])

In [137]:
#delete a value at a given index
np.delete(array,0)

array([72, 42, 75, 28,  1, 90, 95, 30, 56])

In [76]:
array1 = np.random.randint(0,101,10)
array1

array([ 72,  19, 100,  37,  95,  56,  82,  60,  81,  86])

In [77]:
array2 = np.random.randint(0,101,10)
array2

array([48, 38, 82, 27, 86, 18, 89, 19, 46,  9])

In [78]:
array1 + array2

array([120,  57, 182,  64, 181,  74, 171,  79, 127,  95])

In [79]:
array1 - array2

array([ 24, -19,  18,  10,   9,  38,  -7,  41,  35,  77])

In [80]:
array1 * array2

array([3456,  722, 8200,  999, 8170, 1008, 7298, 1140, 3726,  774])

In [81]:
array1 / array2

array([1.5       , 0.5       , 1.2195122 , 1.37037037, 1.10465116,
       3.11111111, 0.92134831, 3.15789474, 1.76086957, 9.55555556])

In [82]:
#we add an element to all items of the numpy array
array1 + 1

array([ 73,  20, 101,  38,  96,  57,  83,  61,  82,  87])

In [83]:
array1 ** 2

array([ 5184,   361, 10000,  1369,  9025,  3136,  6724,  3600,  6561,
        7396])

In [84]:
np.sqrt(array1)

array([ 8.48528137,  4.35889894, 10.        ,  6.08276253,  9.74679434,
        7.48331477,  9.05538514,  7.74596669,  9.        ,  9.2736185 ])

In [85]:
np.max(array1)

100

In [86]:
np.min(array1)

19

In [87]:
np.sin(array1)

array([ 0.25382336,  0.14987721, -0.50636564, -0.64353813,  0.68326171,
       -0.521551  ,  0.31322878, -0.30481062, -0.62988799, -0.92345845])

In [89]:
array1.sort()
array1

array([ 19,  37,  56,  60,  72,  81,  82,  86,  95, 100])

In [96]:
arr1 = np.random.randint(0,101,(3,3))
arr2 = np.random.randint(0,101,(3,3))

In [97]:
#dot product
arr1.dot(arr2)

array([[ 8090,  7178,  5096],
       [13074, 12294, 10920],
       [11770, 11909, 11536]])

In [98]:
arr1

array([[90,  7, 56],
       [94, 51, 96],
       [59, 77, 86]])

In [99]:
np.transpose(arr1)

array([[90, 94, 59],
       [ 7, 51, 77],
       [56, 96, 86]])

In [100]:
arr1.T

array([[90, 94, 59],
       [ 7, 51, 77],
       [56, 96, 86]])

In [54]:
#to get the maximum of an array we use the max() method
vec.max()

100

In [72]:
#the index of the maximum
vec.argmax()

12

In [73]:
#the index of the minimum
vec.argmin()

48

In [55]:
#to get the minimum of an array we use the min() method
vec.min()

1

In [63]:
#lets calculate the mean of a matrix along the columns
mat.max(axis=1)

array([ 95, 100,  72,  92,  89,  84,  68])

In [64]:
#lets calculate the mean of a matrix along the rows
mat.max(axis=0)

array([ 91,  86,  95,  92,  59, 100,  89])

In [66]:
#lets calculate the mean of a matrix along the columns
np.mean(mat,axis=1)

array([51.14285714, 55.14285714, 43.71428571, 41.71428571, 64.85714286,
       41.57142857, 35.42857143])

In [67]:
#lets calculate the mean of a matrix along the rows
np.mean(mat,axis=0)

array([52.42857143, 55.71428571, 55.85714286, 53.71428571, 35.        ,
       41.14285714, 39.71428571])

In [69]:
#the variance of a numpy array
np.var(vec)

837.6551436901291

In [103]:
#the correlation coefficent
vec.sum()

2335

In [104]:
#sum on rows
mat.sum(axis=0)

array([367, 390, 391, 376, 245, 288, 278])

In [106]:
#sum on columns
mat.sum(axis=1)

array([358, 386, 306, 292, 454, 291, 248])

In [110]:
import numpy as np

In [112]:
np.median(vec)

52.0

In [113]:
#Correlation coefficient
np.corrcoef(vec)

1.0

In [114]:
np.std(vec)

28.94227260755674

# Indexing , Selection , Slicing

In [116]:
#first of all we create a numpy array using the arrange function
array = np.arange(0,9)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [120]:
matrix = np.random.randint(0,101,(3,4))
matrix

array([[39, 63,  6, 39],
       [81, 30, 63,  3],
       [56,  7, 63, 49]])

In [117]:
#lets retrieve a value at a given index
array[2]

2

In [118]:
#now we retrieve the values from index 0 till index 5(not inclusive)
array[0:5]

array([0, 1, 2, 3, 4])

In [123]:
#we retrieve the value at (0,0)(row,column)
matrix[1,2]

63

In [125]:
#we retrieve values from the index 0 till index 5(not inclusive)
array[0:5]

array([0, 1, 2, 3, 4])

In [127]:
#we retrieve the intersectin between all the rows and column at index 0
matrix[:,0]

array([39, 81, 56])

In [131]:
#lets look at boolean indexing
array>5


array([False, False, False, False, False, False,  True,  True,  True])

In [132]:
#we get the element that are superior to five
array[array>5]

array([6, 7, 8])